//! Documentation generator: the topology as a page a human can read, with a
//! Mermaid diagram that renders on any code-hosting site.

const std = @import("std");
const schema = @import("../schema.zig");

const Topology = schema.Topology;

pub fn render(comptime t: Topology) []const u8 {
    @setEvalBranchQuota(200_000);
    comptime var out: []const u8 = "# " ++ t.name ++ "\n\n" ++
        "<!-- Generated by ananke from " ++ t.source ++ ". Do not edit. -->\n\n" ++
        std.fmt.comptimePrint(
            "{d} services, {d} permitted connections. Every entry below was checked " ++
                "by the compiler before this file was written.\n\n",
            .{ t.services.len, t.links.len },
        );

    out = out ++ "## Services\n\n" ++
        "| service | tier | image | ports | replicas |\n" ++
        "| --- | --- | --- | --- | --- |\n";
    inline for (t.services) |s| {
        comptime var ports: []const u8 = "";
        inline for (s.ports, 0..) |p, i| {
            ports = ports ++ (if (i == 0) "" else "<br>") ++
                std.fmt.comptimePrint("`{s}` {d}/{s} ({s})", .{ p.name, p.number, p.proto.tag(), p.expose.tag() });
        }
        out = out ++ "| `" ++ s.name ++ "` | " ++ s.zone.tag() ++ " | " ++
            (if (s.image.len == 0) "*built here*" else "`" ++ s.image ++ "`") ++ " | " ++
            (if (ports.len == 0) "-" else ports) ++ " | " ++
            std.fmt.comptimePrint("{d} |\n", .{s.replicas});
    }

    out = out ++ "\n## Permitted connections\n\n";
    if (t.links.len == 0) {
        out = out ++ "None. Every service is isolated.\n";
    } else {
        out = out ++ "| from | to | port | why |\n| --- | --- | --- | --- |\n";
        inline for (t.links) |l| {
            out = out ++ "| `" ++ l.from ++ "` | `" ++ l.to ++ "` | `" ++ l.port ++ "` | " ++
                (if (l.note.len == 0) "-" else l.note) ++ " |\n";
        }
    }

    out = out ++ "\n## Diagram\n\n```mermaid\nflowchart TD\n";
    inline for (@typeInfo(schema.Zone).@"enum".fields) |f| {
        const zone: schema.Zone = @enumFromInt(f.value);
        comptime var body: []const u8 = "";
        inline for (t.services) |s| {
            if (s.zone != zone) continue;
            body = body ++ "        " ++ ident(s.name) ++ "[\"" ++ s.name ++ "\"]\n";
        }
        if (body.len == 0) continue;
        out = out ++ "    subgraph " ++ f.name ++ "\n" ++ body ++ "    end\n";
    }
    inline for (t.links) |l| {
        out = out ++ "    " ++ ident(l.from) ++ " -->|" ++ l.port ++ "| " ++ ident(l.to) ++ "\n";
    }
    return out ++ "```\n";
}

fn ident(comptime s: []const u8) []const u8 {
    comptime var out: []const u8 = "";
    inline for (s) |c| {
        const ok = (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or (c >= '0' and c <= '9');
        out = out ++ [_]u8{if (ok) c else '_'};
    }
    return out;
}
