//! Small comptime string helpers shared by the generators.
//!
//! All of these run while the compiler is running, so they trade efficiency
//! for simplicity: concatenation with `++`, no allocator in sight.

const std = @import("std");

/// Escape a value for use inside a double-quoted YAML scalar.
pub fn yamlQuote(comptime s: []const u8) []const u8 {
    comptime var out: []const u8 = "\"";
    inline for (s) |c| {
        out = out ++ switch (c) {
            '"' => "\\\"",
            '\\' => "\\\\",
            '\n' => "\\n",
            else => &[_]u8{c},
        };
    }
    return out ++ "\"";
}

/// Join strings with a separator.
pub fn join(comptime parts: []const []const u8, comptime sep: []const u8) []const u8 {
    comptime var out: []const u8 = "";
    inline for (parts, 0..) |p, i| {
        out = out ++ (if (i == 0) "" else sep) ++ p;
    }
    return out;
}

/// A YAML flow sequence: `[a, b, c]`.
pub fn flowSeq(comptime parts: []const []const u8) []const u8 {
    return "[" ++ join(parts, ", ") ++ "]";
}

/// Prefix every non-empty line of `s` with `n` spaces.
pub fn indent(comptime s: []const u8, comptime n: usize) []const u8 {
    const pad = " " ** n;
    comptime var out: []const u8 = "";
    comptime var line_start: usize = 0;
    inline for (s, 0..) |c, i| {
        if (c != '\n') continue;
        const line = s[line_start..i];
        out = out ++ (if (line.len == 0) "" else pad) ++ line ++ "\n";
        line_start = i + 1;
    }
    if (line_start < s.len) {
        out = out ++ pad ++ s[line_start..];
    }
    return out;
}

/// A banner explaining that a file is generated, in the comment syntax the
/// target format understands.
pub fn banner(comptime comment: []const u8, comptime topology: []const u8, comptime source: []const u8) []const u8 {
    return comment ++ " Generated by ananke from the '" ++ topology ++ "' topology.\n" ++
        comment ++ " Source of truth: " ++ source ++ "\n" ++
        comment ++ " Do not edit; this file is rewritten by `zig build emit` and every\n" ++
        comment ++ " byte of it was verified before the binary was allowed to exist.\n";
}
